apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-97"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-97"
data:
  mysql.db.name: "{{ .Values.nacos.data.mysql.dbname }}"
  mysql.port: "{{ .Values.nacos.data.mysql.port }}"
  mysql.user: "{{ .Values.nacos.data.mysql.user }}"
  mysql.password: "{{ .Values.nacos.data.mysql.password }}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-97"
spec:
  serviceName: nacos-headless
  replicas: {{ .Values.nacos.replicas }}
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.nacos.images.image }}:{{ .Values.nacos.images.tag }}"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "{{ .Values.nacos.replicas }}"
            - name: INCLOUD_MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: INCLOUD_MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: INCLOUD_MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: INCLOUD_MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: MODE
              value: "standalone"
            #- name: PREFER_HOST_MODE
            #  value: "hostname"
            #- name: NACOS_SERVERS
            #  value: {{ .Values.nacos.servers }}
      #imagePullSecrets:
      #  - name: jcrsecret
  selector:
    matchLabels:
      app: nacos

