name: incloud-biz-study
replicaCount: 1
image:
  repository: dockerhub.kubekey.local/zhongyuanjian/incloud-biz-study
  pullPolicy: Always
  tag: "latest"
  port: 8034
imageEnvConfigMap: incloud-config
