apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-96"
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "redis-cli config set requirepass Netwisd*8" ]
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.image.port }}
          name: {{ .Values.name }}
        env:
          - name: TZ
            value: "Asia/Shanghai"
