apiVersion: v1
kind: Service
metadata:
  name: incloud-redis
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-96"
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: {{ .Values.service.port }}