name: rocketmq
replicaCount: 1
image:
  repository: dockerhub.kubekey.local/netwisd/apache/rocketmq
  pullPolicy: IfNotPresent
  tag: "4.9.3"
  port: 
    broker:
      p1: 10909
      p2: 10911
    namesrv: 9876
service:
  port: 32103