apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-96"
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage