apiVersion: v1
kind: Service
metadata:
  name: incloud-minio
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-96"
spec:
  selector:
    app: minio
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: {{ .Values.service.port }}