name: nginx
replicaCount: 1
image:
  repository: dockerhub.kubekey.local/netwisd/nginx
  pullPolicy: IfNotPresent
  tag: "latest"
  port: 80
data:
  path: 
    html: /data/nginx/html
    conf: /data/nginx/conf
  server:
    html: nfs
    conf: nfs