apiVersion: v1
kind: Service
metadata:
  name: incloud-rocketmq
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-96"
spec:
  selector:
    app: rocketmq
  type: NodePort
  ports:
  - port: 9876
    targetPort: 9876
    nodePort: {{ .Values.service.port }}