apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-99"
provisioner: fuseim.pri/ifs
parameters:
  archiveOnDelete: "false"
